### ISSUE TITLE
Cant reload file with typescript lsp

### ISSUE THREAD

**Issue by Superpat** [9fans/acme-lsp#75]
So the typescript lsp works pretty well when reading a file, I get diagnostics and hover info, but if I modify the file and Put, it's new state is never reloaded. Even if I click on Get in the file and / or Reload in the diagnostics window. 

The only thing to do is restart the lsp or restart acme-lsp on file change, which is a bit annoying haha.

**Comment by Superpat** [comment]
to be clear this is when files are changed inside acme, not by an outside process like #6

**Comment by fhs** [comment]
Reopening because we still need to update acme-lsp's dependency on go-lsp-internal.
